/*
  © 2018 SwiftyCloud OÜ. All rights reserved.
  Contact: info@swifty.cloud
*/

/** PAGE **/
export const SET_HIDDEN_STATUS = 'SET_HIDDEN_STATUS'
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE'
export const SET_APP_LOADING_STATUS = 'SET_APP_LOADING_STATUS'
export const SET_SIGN_LOADING_STATUS = 'SET_SIGN_LOADING_STATUS'
export const SET_FUNCTION_ACTIVE_TAB = 'SET_FUNCTION_ACTIVE_TAB'
export const SET_STATS_ACTIVE_TAB = 'SET_STATS_ACTIVE_TAB'
export const SET_PARENT_PAGE = 'SET_PARENT_PAGE'

/** FUNCTIONS **/
export const SAVE_FUNCTION = 'SAVE_FUNCTION'
export const SAVE_FUNCTION_SOURCES = 'SAVE_FUNCTION_SOURCES'
export const SAVE_FUNCTIONS_LIST = 'SAVE_FUNCTIONS_LIST'
export const SAVE_CURRENT_FUNCTION = 'SAVE_CURRENT_FUNCTION'
export const SAVE_FUNCTION_LANGS = 'SAVE_FUNCTION_LANGS'
export const SAVE_FUNCTION_STATS = 'SAVE_FUNCTION_STATS'

/** BUCKETS **/
export const SAVE_BUCKETS = 'SAVE_BUCKETS'

/** AUTH **/
export const SAVE_USER_INFO = 'SAVE_USER_INFO'
export const SAVE_AUTH_TOKEN = 'SAVE_AUTH_TOKEN'
export const SAVE_USER_ID = 'SAVE_USER_ID'
export const RESET_AUTH_DATA = 'RESET_AUTH_DATA'

/** PROJECTS **/
export const SAVE_PROJECTS_LIST = 'SAVE_PROJECTS_LIST'
export const UPDATE_CURRENT_PROJECT = 'UPDATE_CURRENT_PROJECT'

/** MIDDLEWARES **/
export const SAVE_MIDDLEWARES = 'SAVE_MIDDLEWARES'
export const SAVE_MIDDLEWARE_TYPES = 'SAVE_MIDDLEWARE_TYPES'
